name: data-science-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter
  - ipykernel
  - pyyaml
  - click
  - tqdm
  - pytest
  - pip
  - pip:
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - pandera>=0.15.0
    - mlflow>=2.5.0
    - nbstripout>=0.6.1
    - black>=23.7.0
    - flake8>=6.0.0
    - pre-commit>=3.3.0